require("abc")
require("base64")
require("collections")
require("collections-defaultdict")
require("collections-deque")
require("copy")
require("datetime")
require("fnmatch")
require("functools")
require("gzip")
require("hmac")
require("html")
require("inspect")
require("io")
require("itertools")
require("locale")
require("logging")
require("operator")
require("os")
require("os-path")
require("pathlib")
require("stat")
require("unittest")
require("uu")

# Use local version of urequests that makes use of browser APIs
package("urequests")

# Import package from directory instead of using 'require', so as to
# avoid using mip's manifest.py file
package("mip", base_path="$(MPY_LIB_DIR)/micropython/mip")
